### ISSUE TITLE
下载bing图片的程序运行报错，你那能运行么？

### ISSUE THREAD

**Issue by zkydrx** [gaopu/Java#3]
`org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at BingImages.main(BingImages.java:68)
Caused by: org.apache.http.ProtocolException: Target host is not specified
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:70)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:124)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:183)
	... 3 more
`
说addres未指定，address有值啊？能讲下这个下载的原理是什么？

 ![](https://github.com/zkydrx/images/blob/master/think/bingimage.png?raw=true)

![](https://github.com/zkydrx/images/blob/master/think/bingimage1.png?raw=true)

**Comment by gaopu** [comment]
修改一下正则表达式即可。

**Comment by zkydrx** [comment]
![](https://github.com/zkydrx/images/blob/master/think/regex.png?raw=true)
那这个要怎么修改呢？

**Comment by gaopu** [comment]
你对照着网页修改啊~

**Comment by zkydrx** [comment]
g_img={url: "/az/hprichbg/rb/TuileriesGardenWheel_ZH-CN12655332871_1920x1080.jpg"}
这是资源地址。
![](https://github.com/zkydrx/images/blob/master/think/bingimage2.png?raw=true)
我根据资源地址发现你的代码中正则表达式少了个大括号，于是加上去了。如下截图
![](https://github.com/zkydrx/images/blob/master/think/bingimage3.png?raw=true)
运行，发现没报错了。
![](https://github.com/zkydrx/images/blob/master/think/bingimage4.png?raw=true)
但是目标地址并没有目标图片。
![](https://github.com/zkydrx/images/blob/master/think/bingimage5.png?raw=true)
于是我开始调试。发现address变成了null。这到底是怎么回事？
![](https://github.com/zkydrx/images/blob/master/think/bingimage6.png?raw=true)
